### ISSUE TITLE
Crash when using custom font issues (Vanilla Issue)

### ISSUE THREAD

**Issue by RamiKamado** [RedLime/SpeedRunIGT#13]
my game crashs when i click "font" button in option after i inserted ttf file into "font" folder.

**Comment by RedLime** [comment]
1. what is your fabric loader version?
2. what js your SpeedRunIGT version?
2. also upload your crash log.

**Comment by RamiKamado** [comment]
1. 0.12.8
2. 2.15.1
3.
[hs_err_pid32636.log](https://github.com/RedLime/SpeedRunIGT/files/7779848/hs_err_pid32636.log)

**Comment by RedLime** [comment]
can you send the .tff file here?

**Comment by RamiKamado** [comment]
square.ttf in this file

[squarefont.zip](https://github.com/RedLime/SpeedRunIGT/files/7779907/squarefont.zip)

**Comment by RedLime** [comment]
> square.ttf in this file
> 
> [squarefont.zip](https://github.com/RedLime/SpeedRunIGT/files/7779907/squarefont.zip)
> 

I will testing about this, but It seems some grapics side problem :/
also will tell to you about details after I tested.

**Comment by RedLime** [comment]
![image](https://user-images.githubusercontent.com/25276450/147529747-6ea36a32-a9e9-48e6-a6e1-57d70b0bba7d.png)
Yes, this appears to be a graphic error on some devices.
It seems to be an issue between Minecraft and the graphics (driver). I will find a solution, but it doesn't seem easy.

**Comment by RamiKamado** [comment]
thank you for editing the title. i'm looking forward to your solution :D

**Comment by RedLime** [comment]
### Causes and explanations for this issue for all
This is a compatibility issue between Intel Graphic Driver and OpenGL.
If you see a crash like this issue when using custom fonts, you are possibly using are Intel graphics.
This issue has already been reported on the bug tracker on Vanilla MC and is fixed in the 1.17-snapshot (21w16a).
https://bugs.mojang.com/browse/MC-180529
So this issue may occur in versions 1.14 to 1.16.
### How to solve
Currently there is nothing I can do to resolve with this in SpeedRunIGT codes.
Actually in 1.14 - 1.16 there isn't some ways to solve if you're using Intel graphics.
- Update your graphics driver. (I don't think it will be resolved)
- Use a different graphic. AMD or NVIDIA or something.
- Use version 1.17 or higher.
- Don't use custom font. use default font only.
